### ISSUE TITLE
Option `close_sidebar_if_opened` is not respected

### ISSUE THREAD

**Issue by driutheman** [miguelgraz/FocusFileOnSidebar#11]
Hey,

Great plugin! I realy enjoy it.

Few days ago plugin was updated and `close_sidebar_if_opened` in user preferences file is not respected anymore.

**Comment by yijia-zhan** [comment]
I have the same issue.

**Comment by miguelgraz** [comment]
Hello folks!

Thanks for taking the time to give feedback, these last days we fixed a memory leak bug, probably my tests missed the `close_sidebar_if_opened` configuration, I'll fix that asap, sorry.

Will keep you informed here :snowboarder:

**Comment by driutheman** [comment]
Great. Thanks

**Comment by jhollingworth** [comment]
Any update on this?

**Comment by yijia-zhan** [comment]
While waiting for a new build, you can use `PackageResourceViewer` to open up `FocusFileOnSidebar` and modify `FocusFileOnSidebar.py`.

**Comment by reversefold** [comment]
Having the same issue. @yijia-zhan do you have a proposed change which will fix the issue?

**Comment by ptim** [comment]
keen for a sustainable fix for this - thanks for the workaround @yijia-zhan !
(loving the package, tx!)

**Comment by srigi** [comment]
Please release a fix otherwise this plugin is pointless.

**Comment by cazacugmihai** [comment]
+1 to fix this

**Comment by miguelgraz** [comment]
Sorry for taking ages to address this issue, seriously, my bad.
It was caused by my lack of experience with Python, it was modifying a local variable instead of the global one.

So this issue should be fixed now, I'll close this but please take a minute to test it on your computers and report any problem, being this one or another :)

Thank you very much for taking the time to report this error and for your patience, I really appreciate it!

:snowboarder:
