### ISSUE TITLE
Closes sidebar

### ISSUE THREAD

**Issue by roblav96** [miguelgraz/FocusFileOnSidebar#19]
I do `ctrl+shift+P` and choose `Focus File on Sidebar` and it closes the sidebar. But when I `right-click` text in the file and chose `Reveal in Side Bar` it works fine. I would like to bind `focus_file_on_sidebar` to my own keymap but I can't cause it closes the sidebar insead.

**Comment by miguelgraz** [comment]
Hey @roblav96 

Thanks for taking the time to report it here!

Yeah by default the plugin closes the sidebar if that's opened already, some people had the same complain and because of them I've added a `close_sidebar_if_opened` option to change this behavior, it is hopefully better explained here https://github.com/miguelgraz/FocusFileOnSidebar#configuring

Would you please take a look and try it with a `"close_sidebar_if_opened": false` configuration to see if that's the behavior you'd like to achieve?

Hope this helps, if any issue persists please let me know!

**Comment by roblav96** [comment]
Ah, that's it!

Thank you! 🍰

**Comment by miguelgraz** [comment]
Glad it helped, thanks for using it :heart:

**Comment by roblav96** [comment]
Thanks for supplying it!
